"""
shadow313.v4.finetune_ui.finetune_ui  — v4
LoRA/QLoRA fine-tuning configuration generator for Shadow313-7B.
Generates Unsloth + QLoRA training config with GGUF export for Ollama.
"""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

FINETUNE_CONFIG_TEMPLATE = """# Shadow313 LoRA Fine-Tune Configuration
# Generated: {timestamp}
# Framework: Unsloth + QLoRA (4-bit quantization)
# Target: Shadow313-7B security domain model

model:
  base_model: "unsloth/mistral-7b-v0.3-bnb-4bit"
  max_seq_length: 4096
  dtype: null  # auto-detect
  load_in_4bit: true

lora:
  r: 16
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  lora_alpha: 16
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: false

training:
  dataset: "{dataset_path}"
  dataset_format: "alpaca"  # instruction, input, output format
  output_dir: "{output_dir}"
  batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2.0e-4
  fp16: false
  bf16: false
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407

export:
  format: "gguf"
  quantization: "q4_k_m"
  output_name: "shadow313-7b-{timestamp_short}"
  ollama_import: true
  ollama_model_name: "shadow313:7b"
"""

TRAINING_SCRIPT = '''#!/usr/bin/env python3
"""
Shadow313 LoRA Fine-Tuning Script
Generated by Shadow313 NEXUS v4.0.0
"""
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset
import yaml, sys

def main():
    with open("finetune_config.yaml") as f:
        cfg = yaml.safe_load(f)

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name     = cfg["model"]["base_model"],
        max_seq_length = cfg["model"]["max_seq_length"],
        dtype          = cfg["model"]["dtype"],
        load_in_4bit   = cfg["model"]["load_in_4bit"],
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r                   = cfg["lora"]["r"],
        target_modules      = cfg["lora"]["target_modules"],
        lora_alpha          = cfg["lora"]["lora_alpha"],
        lora_dropout        = cfg["lora"]["lora_dropout"],
        bias                = cfg["lora"]["bias"],
        use_gradient_checkpointing = cfg["lora"]["use_gradient_checkpointing"],
        random_state        = cfg["lora"]["random_state"],
    )

    dataset = load_dataset("json", data_files=cfg["training"]["dataset"], split="train")

    trainer = SFTTrainer(
        model        = model,
        tokenizer    = tokenizer,
        train_dataset= dataset,
        dataset_text_field = "text",
        max_seq_length     = cfg["model"]["max_seq_length"],
        args = TrainingArguments(
            per_device_train_batch_size   = cfg["training"]["batch_size"],
            gradient_accumulation_steps   = cfg["training"]["gradient_accumulation_steps"],
            warmup_steps                  = cfg["training"]["warmup_steps"],
            max_steps                     = cfg["training"]["max_steps"],
            learning_rate                 = cfg["training"]["learning_rate"],
            fp16                          = cfg["training"]["fp16"],
            bf16                          = cfg["training"]["bf16"],
            logging_steps                 = cfg["training"]["logging_steps"],
            optim                         = cfg["training"]["optim"],
            weight_decay                  = cfg["training"]["weight_decay"],
            lr_scheduler_type             = cfg["training"]["lr_scheduler_type"],
            seed                          = cfg["training"]["seed"],
            output_dir                    = cfg["training"]["output_dir"],
        ),
    )

    print("Starting Shadow313 fine-tuning...")
    trainer.train()

    # Export to GGUF for Ollama
    model.save_pretrained_gguf(
        cfg["export"]["output_name"],
        tokenizer,
        quantization_method = cfg["export"]["quantization"],
    )
    print(f"Model exported: {cfg['export']['output_name']}.gguf")

    if cfg["export"]["ollama_import"]:
        import subprocess
        subprocess.run([
            "ollama", "create", cfg["export"]["ollama_model_name"],
            "-f", f"{cfg['export']['output_name']}.Modelfile"
        ])
        print(f"Ollama model created: {cfg['export']['ollama_model_name']}")

if __name__ == "__main__":
    main()
'''

ALPACA_EXAMPLE = {
    "instruction": "Analyse this CVE and provide a risk assessment.",
    "input": "CVE-2024-1234: Buffer overflow in OpenSSH 9.x allows remote code execution.",
    "output": (
        "Risk Assessment: CRITICAL\n"
        "Vulnerability Class: Buffer Overflow (CWE-120)\n"
        "CVSS v3.1: 9.8 (Critical)\n"
        "Attack Vector: Network / No Authentication Required\n"
        "Impact: Remote Code Execution as root\n"
        "Immediate Actions:\n"
        "1. Patch OpenSSH to latest version immediately\n"
        "2. Restrict SSH access to known IPs via firewall\n"
        "3. Enable fail2ban or equivalent brute-force protection\n"
        "4. Review SSH audit logs for exploitation attempts\n"
        "EPSS Score: 0.94 (94th percentile — actively exploited)\n"
        "KEV Status: Listed in CISA KEV — federal agencies must patch within 3 days"
    ),
}


class FineTuneModule:
    """shadow313.v4.finetune_ui — LoRA fine-tuning config generator. Registered: finetune"""

    def __init__(self, kernel) -> None:
        self.kernel = kernel
        self.out    = kernel.out
        self.session= kernel.session

    def register(self, kernel) -> None:
        kernel.register("finetune", self.run)

    def run(
        self,
        generate_config: bool = False,
        dataset_path: str = "shadow313_training_data.jsonl",
        output_dir: str = "./shadow313-7b-output",
        generate_dataset: bool = False,
        dataset_size: int = 100,
    ) -> dict:
        self.out.section("SHADOW313 FINE-TUNE CONFIGURATION")
        result: dict[str, Any] = {}

        if generate_config:
            ts       = datetime.now(timezone.utc).isoformat()
            ts_short = datetime.now().strftime("%Y%m%d")
            config   = FINETUNE_CONFIG_TEMPLATE.format(
                timestamp       = ts,
                timestamp_short = ts_short,
                dataset_path    = dataset_path,
                output_dir      = output_dir,
            )
            config_path = Path("finetune_config.yaml")
            config_path.write_text(config)
            self.out.success(f"Config generated → {config_path}")

            script_path = Path("finetune.py")
            script_path.write_text(TRAINING_SCRIPT)
            self.out.success(f"Training script → {script_path}")

            result["config_path"] = str(config_path)
            result["script_path"] = str(script_path)
            self.out.info("Install deps: pip install unsloth trl datasets peft")
            self.out.info("Run training: python finetune.py")

        if generate_dataset:
            self.out.info(f"Generating {dataset_size} training examples …")
            examples = self._generate_training_data(dataset_size)
            ds_path  = Path(dataset_path)
            with open(ds_path, "w") as fh:
                for ex in examples:
                    fh.write(json.dumps(ex) + "\n")
            self.out.success(f"Dataset → {ds_path} ({len(examples)} examples)")
            result["dataset_path"] = str(ds_path)
            result["examples"]     = len(examples)

        return result

    def _generate_training_data(self, count: int) -> list[dict]:
        """Generate training examples from session findings using AI."""
        examples = [ALPACA_EXAMPLE]  # seed example

        findings = (self.session.read("findings.json") or {}).get("findings", [])
        for f in findings[:count]:
            cve  = f.get("cve", "")
            desc = f.get("description", "")
            if not cve or not desc:
                continue
            answer = self.kernel.ai.chat(
                f"Provide a detailed security analysis for {cve}: {desc[:200]}. "
                f"Include: risk level, attack vector, immediate actions, CVSS context.",
            )
            examples.append({
                "instruction": "Analyse this CVE and provide a risk assessment.",
                "input":       f"{cve}: {desc[:300]}",
                "output":      answer,
            })

        return examples[:count]