"""
shadow313.v2.reports.pdf_report  — v4
Professional PDF/HTML security reports with AI executive summaries.
WeasyPrint → HTML fallback auto-activates.
"""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Shadow313 Security Report</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; background: #f8f9fa; }}
  h1 {{ color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; border-left: 4px solid #e94560; padding-left: 12px; }}
  h3 {{ color: #0f3460; }}
  .cover {{ text-align: center; padding: 60px 0; background: #0f3460; color: white; border-radius: 8px; margin-bottom: 40px; }}
  .cover h1 {{ color: white; border-color: #e94560; }}
  .risk-badge {{ display: inline-block; padding: 8px 20px; border-radius: 20px; font-weight: bold; font-size: 1.2em; }}
  .risk-CRITICAL {{ background: #e94560; color: white; }}
  .risk-HIGH {{ background: #ff6b35; color: white; }}
  .risk-MEDIUM {{ background: #ffd166; color: #333; }}
  .risk-LOW {{ background: #06d6a0; color: white; }}
  table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
  th {{ background: #0f3460; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #dee2e6; }}
  tr:nth-child(even) {{ background: #f1f3f5; }}
  .finding-critical {{ border-left: 4px solid #e94560; padding: 10px; margin: 10px 0; background: #fff5f5; }}
  .finding-high {{ border-left: 4px solid #ff6b35; padding: 10px; margin: 10px 0; background: #fff8f5; }}
  .finding-medium {{ border-left: 4px solid #ffd166; padding: 10px; margin: 10px 0; background: #fffdf0; }}
  .finding-low {{ border-left: 4px solid #06d6a0; padding: 10px; margin: 10px 0; background: #f0fff8; }}
  .exec-summary {{ background: #e8f4fd; border: 1px solid #bee3f8; border-radius: 8px; padding: 20px; margin: 20px 0; }}
  .receipt {{ background: #1a1a2e; color: #00ff88; font-family: monospace; padding: 15px; border-radius: 6px; font-size: 0.85em; }}
  footer {{ text-align: center; color: #6c757d; margin-top: 60px; font-size: 0.85em; }}
</style>
</head>
<body>

<div class="cover">
  <h1>🔒 Shadow313 NEXUS Security Report</h1>
  <p>Session: {session_id}</p>
  <p>Target: {target}</p>
  <p>Date: {scan_date}</p>
  <p>Overall Risk: <span class="risk-badge risk-{risk_rating}">{risk_rating}</span></p>
</div>

<h2>Executive Summary</h2>
<div class="exec-summary">
{executive_summary}
</div>

<h2>Risk Matrix</h2>
<table>
  <tr><th>Severity</th><th>Count</th><th>Action Required</th></tr>
  <tr><td>🔴 CRITICAL</td><td>{critical_count}</td><td>Immediate remediation required</td></tr>
  <tr><td>🟠 HIGH</td><td>{high_count}</td><td>Remediate within 7 days</td></tr>
  <tr><td>🟡 MEDIUM</td><td>{medium_count}</td><td>Remediate within 30 days</td></tr>
  <tr><td>🟢 LOW</td><td>{low_count}</td><td>Schedule for next maintenance window</td></tr>
</table>

<h2>Detailed Findings</h2>
{findings_html}

{recon_section}

<h2>Cryptographic Provenance (313-BIND)</h2>
<div class="receipt">
{receipt_info}
</div>

<footer>
  Generated by Shadow313 NEXUS v4.0.0 | {scan_date}<br>
  Every finding in this report is cryptographically bound with a 313-BIND receipt.<br>
  This report is for authorized security assessment use only.
</footer>
</body>
</html>"""


def _severity_order(sev: str) -> int:
    return {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}.get(sev.upper(), 4)


def _compute_risk_rating(findings: list[dict]) -> str:
    if any(f.get("severity","").upper() == "CRITICAL" for f in findings):
        return "CRITICAL"
    if any(f.get("severity","").upper() == "HIGH" for f in findings):
        return "HIGH"
    if any(f.get("severity","").upper() == "MEDIUM" for f in findings):
        return "MEDIUM"
    if findings:
        return "LOW"
    return "LOW"


def _findings_to_html(findings: list[dict]) -> str:
    if not findings:
        return "<p>No findings recorded.</p>"
    html = []
    for f in sorted(findings, key=lambda x: _severity_order(x.get("severity","LOW")))[:50]:
        sev   = f.get("severity", "LOW").lower()
        cve   = f.get("cve", "")
        cvss  = f.get("cvss_v3", "")
        desc  = f.get("description", "")[:300]
        html.append(
            f'<div class="finding-{sev}">'
            f'<strong>[{sev.upper()}] {cve}</strong>'
            f'{f" — CVSS: {cvss}" if cvss else ""}'
            f'<br><small>{desc}</small>'
            f'</div>'
        )
    return "\n".join(html)


def _recon_to_html(recon: dict) -> str:
    if not recon:
        return ""
    html = ["<h2>Reconnaissance Appendix</h2>"]
    dns = recon.get("dns", {})
    if dns:
        html.append("<h3>DNS Records</h3><table><tr><th>Type</th><th>Records</th></tr>")
        for rtype, records in dns.items():
            html.append(f"<tr><td>{rtype}</td><td>{', '.join(str(r) for r in records)}</td></tr>")
        html.append("</table>")
    ports = recon.get("ports", [])
    if ports:
        html.append("<h3>Open Ports</h3><table><tr><th>Port</th><th>State</th><th>Banner</th></tr>")
        for p in ports[:20]:
            html.append(f"<tr><td>{p.get('port','')}</td><td>{p.get('state','')}</td><td>{p.get('banner','')[:60]}</td></tr>")
        html.append("</table>")
    return "\n".join(html)


class ReportGenerator:
    """Generates HTML/PDF security reports."""

    def __init__(self, output_dir: str = "~/.shadow313/reports") -> None:
        self._dir = Path(output_dir).expanduser()
        self._dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        session_id: str,
        findings: list[dict],
        recon: dict,
        executive_summary: str,
        receipt_info: str = "",
        target: str = "",
        output_format: str = "html",
    ) -> str:
        scan_date    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        risk_rating  = _compute_risk_rating(findings)
        sev_counts   = {s: sum(1 for f in findings if f.get("severity","").upper() == s)
                        for s in ("CRITICAL","HIGH","MEDIUM","LOW")}

        html = REPORT_HTML_TEMPLATE.format(
            session_id       = session_id[:16],
            target           = target or "Multiple Targets",
            scan_date        = scan_date,
            risk_rating      = risk_rating,
            executive_summary= executive_summary.replace("\n", "<br>"),
            critical_count   = sev_counts.get("CRITICAL", 0),
            high_count       = sev_counts.get("HIGH", 0),
            medium_count     = sev_counts.get("MEDIUM", 0),
            low_count        = sev_counts.get("LOW", 0),
            findings_html    = _findings_to_html(findings),
            recon_section    = _recon_to_html(recon),
            receipt_info     = receipt_info or "No 313-BIND receipt (temporal binding disabled)",
        )

        # Save HTML
        html_path = self._dir / f"report_{session_id[:8]}_{datetime.now().strftime('%Y%m%d')}.html"
        html_path.write_text(html)

        if output_format == "pdf":
            pdf_path = html_path.with_suffix(".pdf")
            if self._try_weasyprint(html, str(pdf_path)):
                return str(pdf_path)
            return str(html_path)  # fallback to HTML

        return str(html_path)

    def _try_weasyprint(self, html: str, output_path: str) -> bool:
        try:
            from weasyprint import HTML
            HTML(string=html).write_pdf(output_path)
            return True
        except ImportError:
            return False
        except Exception:
            return False


class ReportModule:
    """shadow313.v2.reports — PDF/HTML report generation. Registered: report"""

    def __init__(self, kernel) -> None:
        self.kernel  = kernel
        self.out     = kernel.out
        self.session = kernel.session
        cfg          = kernel.config.get("reports", default={})
        self.generator = ReportGenerator(cfg.get("output_dir", "~/.shadow313/reports"))

    def register(self, kernel) -> None:
        kernel.register("report", self.run)

    def run(
        self,
        from_session: str = "",
        from_campaign: str = "",
        output: str = "",
        format: str = "html",
        _prev_result: dict | None = None,
    ) -> dict:
        self.out.section("SECURITY REPORT GENERATOR")

        # Load session data
        if from_session:
            from shadow313.core.session import Session
            s = Session.resume(from_session)
        else:
            s = self.session

        findings = (s.read("findings.json") or {}).get("findings", [])
        recon    = s.read("recon.json") or {}
        target   = recon.get("target", s.target)

        # Get 313-BIND receipt info
        receipt_info = ""
        temporal = self.kernel.get_module("temporal")
        if temporal:
            receipts = temporal.engine.list_receipts(limit=1)
            if receipts:
                r = receipts[0]
                receipt_info = (
                    f"Receipt ID:  {r.get('receipt_id','')}\n"
                    f"Timestamp:   {r.get('timestamp_iso','')}\n"
                    f"SHA3-512:    {r.get('sha3_512','')[:32]}…\n"
                    f"Algorithm:   {r.get('algorithm','')}\n"
                    f"IPFS CID:    {r.get('ipfs_cid','')}"
                )

        # Generate AI executive summary
        self.out.info("Generating AI executive summary …")
        exec_summary = self.kernel.ai.chat(
            "Write a concise executive security summary (3-4 paragraphs) for a CISO. "
            "Include: overall risk posture, top 3 critical findings, business impact, "
            "and immediate recommended actions. Use professional language.",
            context={
                "findings_count": len(findings),
                "target":         target,
                "top_findings":   findings[:10],
                "recon_summary":  {k: v for k, v in recon.items() if k in ("target","dns","ports")},
            },
        )

        # Generate report
        self.out.info(f"Generating {format.upper()} report …")
        report_path = self.generator.generate(
            session_id        = s.id,
            findings          = findings,
            recon             = recon,
            executive_summary = exec_summary,
            receipt_info      = receipt_info,
            target            = target,
            output_format     = format,
        )

        self.out.success(f"Report generated → {report_path}")
        return {"report_path": report_path, "findings": len(findings), "target": target}